In [1]:
import torch
import torch.nn as nn

In [2]:
import torch.nn.functional as F

In [7]:
import torch.optim as optim

In [3]:
x_train = torch.FloatTensor([[2, 3], [5, 8], [6, 9]])
y_train = torch.FloatTensor([9, 12, 16])

print(x_train.shape, y_train.shape)

torch.Size([3, 2]) torch.Size([3])


In [5]:
y_train = y_train.unsqueeze(dim=-1)
print(y_train)
print(y_train.shape)

tensor([[ 9.],
        [12.],
        [16.]])
torch.Size([3, 1])


In [6]:
model = nn.Linear(2, 1)

In [9]:
optimizer = optim.SGD(model.parameters(), lr = 0.01)

In [10]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.0662,  0.1213]], requires_grad=True), Parameter containing:
tensor([-0.1870], requires_grad=True)]


In [11]:
print(type(model))

<class 'torch.nn.modules.linear.Linear'>


In [13]:
nb_epochs = 10

for epoch in range(nb_epochs + 1):
    
    hypothesis = model(x_train)
    
    cost = F.mse_loss(hypothesis, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print("epoch : {:2d}, cost : {:.8f}".format(epoch, cost.item()))
    

epoch :  0, cost : 151.19079590
epoch :  1, cost : 38.86724472
epoch :  2, cost : 13.28629780
epoch :  3, cost : 7.44618797
epoch :  4, cost : 6.09875727
epoch :  5, cost : 5.77385712
epoch :  6, cost : 5.68175697
epoch :  7, cost : 5.64273119
epoch :  8, cost : 5.61587477
epoch :  9, cost : 5.59188223
epoch : 10, cost : 5.56862783
