In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
a = [1, 2, 3, 4, 5]

b = np.array(a)
print(a, b)

[1, 2, 3, 4, 5] [1 2 3 4 5]


In [11]:
np.ones(5).tolist()

[1.0, 1.0, 1.0, 1.0, 1.0]

In [12]:
np.array([[1, 2, 3], [4, 5, 6]], dtype='double')

array([[1., 2., 3.],
       [4., 5., 6.]])

In [13]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
np.random.random(10)

array([0.72671365, 0.3762294 , 0.22213435, 0.68292772, 0.49603884,
       0.77059686, 0.00283999, 0.30143523, 0.40534246, 0.79922634])

In [15]:
x = np.array([10, 20, 30, 40, 50])

In [16]:
x[0]

10

In [17]:
x[0:2]

array([10, 20])

In [18]:
X = np.array([[1, 2, 3], [4,5,6]])

In [19]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
X.shape()

TypeError: 'tuple' object is not callable

In [21]:
X.shape


(2, 3)

In [22]:
X[0,1]

2

In [23]:
X[0, :]

array([1, 2, 3])

In [24]:
X[:, 1]

array([2, 5])

In [25]:
X[:, [0, 2]]

array([[1, 3],
       [4, 6]])

In [26]:
a = np.array([1, 2, 3])
b = a

In [27]:
print(id(a))
print(id(b))

2118515540496
2118515540496


In [29]:
a[0] = 4
print(b)

[4 2 3]


In [30]:
c = a.copy()
a[2] = 1
print(c)
print(a)

[4 2 3]
[4 2 1]


In [31]:
print(a.mean())

2.3333333333333335


In [32]:
a = np.arange(1, 7)

In [33]:
a

array([1, 2, 3, 4, 5, 6])

In [34]:
a.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
a.shape

(6,)

In [36]:
Z = a.reshape(2, 3)

In [37]:
Z

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
Z.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [39]:
Z.flatten()

array([1, 2, 3, 4, 5, 6])

In [40]:
Z.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [41]:
def listlog(vals):
    print(np.log(y) for y in vals)

In [42]:
listlog(Z)

<generator object listlog.<locals>.<genexpr> at 0x000001ED43A035F0>
